---
- name: to check WSUS server if patches are waiting to be approved
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Build a list of all the clusters
    vmware.vmware_rest.vcenter_cluster_info:
      vcenter_hostname: vcsa.DOWNS.LAN
      vcenter_password: LOvemywife%1
      vcenter_username: administrator@vsphere.local
    register: all_the_clusters
