---
- name: to check WSUS server if patches are waiting to be approved
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Build a list of all the clusters
    vmware.vmware_rest.vcenter_vm_info:
    register: existing_vms
    until: existing_vms is not failed
      vcenter_hostname: vcsa.DOWNS.LAN
      vcenter_password: LOvemywife%1
      vcenter_username: administrator@vsphere.local
  
