---
- name: to check WSUS server if patches are waiting to be approved
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Build a list of all the clusters
    vmware.vmware_rest.vcenter_cluster_info:
    register: all_the_clusters
