---
- hosts: "{{ host }}"
  gather_facts: false
  tasks:
  - name: Check for missing updates
    win_updates:
      category_names:
        - Updates
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - DefinitionUpdates
        - WindowsDefender
        - Drivers
        - Tools
      state: searched
    register: kb
  - name: List missing updates
    debug:
      var: kb.updates
