---
- hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Enable Remote Desktop
    win_shell:
      Get-WsusServer "hyperv" | Invoke-WsusServerCleanup -CleanupObsoleteComputers -CleanupObsoleteUpdates
