---
- hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Checkin
    ansible.windows.win_updates:
      category_names: 
        - SecurityUpdates
        - CriticalUpdates
      state: searched
