---
- hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Approve DEV Updates
    win_shell:
       Get-WsusUpdate -Classification "{{ update_class }}" -Approval Unapproved -Status Needed | Approve-WsusUpdate -Action Install -TargetGroupName "{{ approved_group }}"
