---
- name: Forces a client checkin to WSUS server
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Checkin
    win_updates:
      category_names: 
        - SecurityUpdates
        - CriticalUpdates
      state: searched
    when: guest.guestFamily == "windowsGuest"
  - name: Trigger Poll
    win_shell:
      wuauclt /reportnow
    when: guest.guestFamily == "windowsGuest"
