---
- hosts: "{{ ansible_play_batch }}"
  gather_facts: true
  tasks:
  - name: Approve PROD Updates
    win_shell:
       Get-WsusUpdate -Classification All -Approval Approved | Approve-WsusUpdate -Action Install -TargetGroupName "{{ approved_group }}"
