---
- hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Check for missing updates
    win_updates:
      category_names:
        - Updates
        - SecurityUpdates
        - CriticalUpdates
        - DefinitionUpdates
      state: searched
    register: kb
  - name: List missing updates
    debug:
      var: kb.updates
