---
- name: to check WSUS server if patches are waiting to be approved
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Check Critical Updates
    win_shell:
       Get-WsusUpdate -Classification critical -Approval Unapproved -Status Needed
    register: udpates
  - name: Critical Updates Needed Approved
    debug:
      var: updates.stdout_lines
  - name: Check Security Updates
    win_shell:
       Get-WsusUpdate -Classification security -Approval Unapproved -Status Needed
    register: updates
  - name: Security Updates Needed Approved
    debug:
      var: updates.stdout_lines
