---
- name: to check WSUS server if patches are waiting to be approved
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Approve Critical Updates
    win_shell:
       Get-WsusUpdate -Classification critical -Approval AnyExceptDeclined -Status Needed
